### ISSUE TITLE
diable_hdf5_locking

### ISSUE THREAD

**Issue by nihargupte-ph** [dingo-gw/dingo#193]
Installing a fresh environment and running dingo_pipe gives me the following error

```
Traceback (most recent call last):
  File "/home/n/Documents/Research/Dingo/dingo/dingo-venv/bin/dingo_pipe", line 8, in <module>
    sys.exit(main())
  File "/home/n/Documents/Research/Dingo/dingo/dingo/pipe/main.py", line 326, in main
    generate_dag(inputs, model_args)
  File "/home/n/Documents/Research/Dingo/dingo/dingo/pipe/dag_creator.py", line 64, in generate_dag
    generation_node = GenerationNode(inputs, **kwargs)
  File "/home/n/Documents/Research/Dingo/dingo/dingo/pipe/nodes/generation_node.py", line 12, in __init__
    super().__init__(inputs, **kwargs)
  File "/home/n/Documents/Research/Dingo/dingo/dingo-venv/lib/python3.8/site-packages/bilby_pipe/job_creation/nodes/generation_node.py", line 25, in __init__
    super().__init__(inputs)
  File "/home/n/Documents/Research/Dingo/dingo/dingo-venv/lib/python3.8/site-packages/bilby_pipe/job_creation/node.py", line 27, in __init__
    self.disable_hdf5_locking = inputs.disable_hdf5_locking
AttributeError: 'MainInput' object has no attribute 'disable_hdf5_locking'
```

Not sure why it is happening, but it can be fixed by setting disable_hdf5_locking. Though I'm not sure if this is the correct solution and maybe it's better to set the attribute based on settings provided by the user.

**Comment by stephengreen** [comment]
This seems to be a new flag in `bilby_pipe`, https://git.ligo.org/lscsoft/bilby_pipe/-/merge_requests/529. When it's not set, newer versions of `bilby_pipe` will raise an error because they look for this flag.

We should update `dingo_pipe` to incorporate the flag in the same way, since it solves some issues described in the linked thread. In general, we need to watch for updates to `bilby_pipe` that could break `dingo_pipe`, since `dingo_pipe` is based so closely on `bilby_pipe`.
