### ISSUE TITLE
Error with Generating a waveform dataset

### ISSUE THREAD

**Issue by PawanGu** [dingo-gw/dingo#208]
Hi, 
I first made a conda env and install dingo-gw:
`mamba create -n dingo_env python=3.10 dingo-gw`
After that, I am using this command `dingo_generate_dataset --settings waveform_dataset_settings.yaml --out_file training_data/waveform_dataset.hdf5` to generate waveform dataset. But I get the following error. Please have a look.

Traceback (most recent call last):
  File "/home/pawan.gupta/.conda/envs/dingo_env/bin/dingo_generate_dataset", line 6, in <module>
    from dingo.gw.dataset.generate_dataset import main
  File "/home/pawan.gupta/.conda/envs/dingo_env/lib/python3.10/site-packages/dingo/gw/dataset/__init__.py", line 1, in <module>
    from .generate_dataset import generate_dataset, generate_parameters_and_polarizations
  File "/home/pawan.gupta/.conda/envs/dingo_env/lib/python3.10/site-packages/dingo/gw/dataset/generate_dataset.py", line 11, in <module>
    from torchvision.transforms import Compose
  File "/home/pawan.gupta/.conda/envs/dingo_env/lib/python3.10/site-packages/torchvision/__init__.py", line 5, in <module>
    import torch
  File "/home/pawan.gupta/.conda/envs/dingo_env/lib/python3.10/site-packages/torch/__init__.py", line 228, in <module>
    _load_global_deps()
  File "/home/pawan.gupta/.conda/envs/dingo_env/lib/python3.10/site-packages/torch/__init__.py", line 187, in _load_global_deps
    raise err
  File "/home/pawan.gupta/.conda/envs/dingo_env/lib/python3.10/site-packages/torch/__init__.py", line 168, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/pawan.gupta/.conda/envs/dingo_env/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/pawan.gupta/.conda/envs/dingo_env/lib/python3.10/site-packages/torch/lib/../../../../libmkl_gnu_thread.so.2: undefined symbol: mkl_sparse_c_csr_seq_nt_sym_full_u_mv_i8

**Comment by stephengreen** [comment]
@PawanGu Is this still a problem?

**Comment by annalena-k** [comment]
Close issue due to inactivity.
